name: C++ local tests

permissions:
  contents: read
  pull-requests: write
  issues: write

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        working-directory: ./arduino/
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./arduino/
        run: make local_test
